export const frCA = {
  brand: {
    product: "ACM Studio",
    by: "par Ocliq",
  },
  common: {
    demo: "Données de démonstration",
    saved: "Toutes les modifications sont enregistrées",
    search: "Rechercher une adresse, un client…",
    preview: "Aperçu client",
    continue: "Continuer vers les ajustements",
    back: "Retour",
    close: "Fermer",
  },
  nav: [
    "Vue d’ensemble",
    "Analyses",
    "Propriétés",
    "Contacts",
    "Opportunités",
    "Tâches",
    "Modèles",
    "Statistiques",
    "Paramètres",
  ],
  steps: [
    { short: "Client", title: "Client" },
    { short: "Propriété", title: "Propriété" },
    { short: "Comparables", title: "Comparables" },
    { short: "Ajustements", title: "Ajustements" },
    { short: "Marché", title: "Marché" },
    { short: "Stratégie", title: "Stratégie" },
    { short: "Présentation", title: "Présentation" },
    { short: "Partager", title: "Validation et partage" },
  ],
  analysis: {
    eyebrow: "Analyse en préparation",
    title: "218, rue des Pins",
    location: "Rouyn-Noranda, Québec",
    client: "Pour Marianne et Simon",
    updated: "Mise à jour il y a quelques secondes",
  },
  comparables: {
    eyebrow: "Étape 3 sur 8",
    title: "Choisir les bonnes propriétés comparables",
    intro:
      "Retenez les propriétés qui racontent le mieux la valeur de la maison. Les écarts importants sont signalés, jamais corrigés automatiquement.",
    add: "Ajouter un comparable",
    selected: "retenues",
    filterAll: "Toutes",
    sold: "Vendues",
    active: "En vigueur",
    expired: "Expirées",
    query: "Rechercher dans les comparables",
    table: "Liste",
    cards: "Cartes",
    map: "Carte",
    include: "Retenir",
    excluded: "Écartée",
    reference: "Prix de référence",
    adjustment: "Ajustement suggéré",
    adjusted: "Valeur ajustée",
    source: "Source manuelle",
    noIntegration: "Aucune intégration Centris/MLS connectée",
  },
  insight: {
    eyebrow: "Lecture en temps réel",
    title: "La sélection est cohérente",
    body:
      "Les cinq propriétés retenues forment un échantillon assez proche et récent pour passer aux ajustements.",
    range: "Fourchette observée",
    median: "Médiane vendue",
    distance: "Distance médiane",
    confidence: "Qualité de l’échantillon",
    checks: "Points de vigilance",
    check1: "4 ventes datent de moins de 90 jours",
    check2: "Toutes sont à moins de 3 km",
    warning: "1 propriété nécessite une justification",
  },
  preview: {
    badge: "Aperçu de la présentation",
    title: "Analyse comparative du marché",
    prepared: "Préparée spécialement pour Marianne et Simon",
    address: "218, rue des Pins, Rouyn-Noranda",
    date: "4 août 2026",
    start: "Découvrir l’analyse",
    broker: "Gabriel Arseneault",
    role: "Courtier immobilier résidentiel indépendant",
    note: "Cet aperçu utilise des données fictives de démonstration.",
  },
} as const;

export type LocaleCopy = typeof frCA;
